### ISSUE TITLE
Please help me understand the optical rotary encoder circuit

### ISSUE THREAD

**Issue by wzkres** [RandomDelta6/USB-Mouse#1]
Hi,

Thanks for this great open source mouse project, really learned a lot! I've been trying to understand how the mouse wheel work in the circuit, is LQ1 a dual phototransistor? How would the MCU sense wheel rotating direction with only one pin (one of the emitter?) connected to it?

Regards

**Comment by RandomDelta6** [comment]
LQ1 is indeed a dual LDR. It detects which way the scroll wheel is moving by comparing the change in resistances across both the LDRs . Lets say there is no resistance change in either LDR. It means the scroll wheel is static. If resistance of LDR1 decreases while resistance of LDR 2 increases, it means that the level of illumination on LDR1 is increasing while its decreasing on LDR2 , let's say it corroborates to scrolling down. The opposite change in resistance across the LDRs will indicate scrolling in Up direction. After one cycle of brightness change, the logic is flipped as brightness will increase-decrease-increase when scrolled along the same direction. The rate of change of resistance will indicate how fast the scroll wheel is being spun. It is necessary that the slits on the scroll wheel are spaced apart exactly as per specification so that under no circumstance would both LDRs be completely exposed or completely in shadow.

The chosen MCU has preflashed logic for filtering and decoding scroll logic based off analog output of LQ1. it is actually connected to two pins, pin 4 and pin 3 of the MCU. Pin 3 is also shared with the led, which allows the brightness to be varied with respect to output across one of the internal LDRs of LQ1 which allows it to figure the direction of rotation with more accuracy.

**Comment by wzkres** [comment]
Thank you so much!
